name: build-and-release
on: [workflow_dispatch]
jobs:
  build-creator:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Setup Java Envirionment
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt-hotspot
          java-version: 11
      
      - name: Building with Gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: 5.6.4
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: 'build -x lint'
      
      - name: Tree Diagram of /home
      - run: sudo apt-get install tree
      - run: cd /home && tree
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is an Automatic Release by GitHub Actions."
