name: build-sdl2-android

on:
  push:
    tags:
    - v*

jobs:
  build-curator:
    name: Build Android example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
