name: build-and-release
on: [workflow_dispatch]
jobs:
  build-creator:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Setup Java Envirionment
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt-hotspot
          java-version: 11
      
      - name: Building with Gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: 5.6.4
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: 'build -x lint'
      
      - name: Upload APK Files to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./app/build/outputs/apk/arm/debug/app-arm-debug.apk
            ./app/build/outputs/apk/arm/release/app-arm-release-unsigned.apk
            ./app/build/outputs/apk/arm64/debug/app-arm64-debug.apk
            ./app/build/outputs/apk/arm64/release/app-arm64-release-unsigned.apk
            ./app/build/outputs/apk/x86/debug/app-x86-debug.apk
            ./app/build/outputs/apk/x86/release/app-x86-release-unsigned.apk
            ./app/build/outputs/apk/x86_64/debug/app-x86_64-debug.apk
            ./app/build/outputs/apk/x86_64/release/app-x86_64-release-unsigned.apk
            ./app/build/outputs/apk/all_in_one/debug/app-all_in_one-debug.apk
            ./app/build/outputs/apk/all_in_one/release/app-all_in_one-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          body: "This is an Automatic Release by GitHub Actions. APKs marked "unsigned" needs to be signed with test key before installing. This may change in Future."
